// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsccivnoxffgpzlbbizb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zY2Npdm5veGZmZ3B6bGJiaXpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDUxMzgsImV4cCI6MjA2MzU4MTEzOH0.Mu5wh6Zxilyx2HNlHU4b8WcOPa48LmpoSZbu2YI6_I8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);